// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygoxqrvmjkmtparsetza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnb3hxcnZtamttdHBhcnNldHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4MDExMjksImV4cCI6MjA1MjM3NzEyOX0.jL7Ia1UW18_jn6jSIZumIufEvpuy1DhEZEJOBCRgQyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);